const mysql = require('mysql2/promise');

const descriptions = {
  '100mA Fixed X-Ray Machine With Horizontal Bucky Table': `<p>The <strong>100mA Fixed X-Ray Machine with Horizontal Bucky Table</strong> is a state-of-the-art diagnostic imaging solution engineered for exceptional precision and ease of use in clinical and hospital settings. Manufactured by Sunmax, it features a robust stationary anode tube and a microprocessor-controlled high-voltage generator to ensure consistent, high-contrast radiography.</p><p>Its horizontal Bucky table is designed for maximum patient comfort while offering flexible positioning for a wide range of examinations, including chest, orthopedic, and general radiography. Built with stringent safety standards (AERB/BIS approved), this machine is an essential investment for reliable, daily diagnostic workflows.</p>`,
  '300mA X-Ray Machine': `<p>The <strong>300mA X-Ray Machine</strong> by Sunmax delivers powerful, high-resolution diagnostic capabilities ideal for mid-to-large sized medical facilities. With enhanced generator capacity and refined electronic controls, this machine ensures short exposure times, reducing patient motion artifacts and improving overall image clarity.</p><p>It features a user-friendly console with digital displays for kVp, mA, and mAs, providing technicians with intuitive, precise control over exposure parameters. Built for durability and high throughput, the 300mA model handles complex orthopedic, pulmonary, and general radiographic procedures with exceptional reliability.</p>`,
  'SUNMAX SPICA 40kW HF Digital Radiography System': `<p>The <strong>SUNMAX SPICA 40kW HF Digital Radiography System</strong> represents the pinnacle of modern X-ray technology. Utilizing a High-Frequency (HF) generator, this advanced DR system minimizes soft radiation, significantly lowering patient dose while producing incredibly sharp, artifact-free digital images in seconds.</p><p>Designed for high-volume hospitals and specialized diagnostic centers, it integrates seamlessly with flat-panel detectors (FPD) and PACS networks. Its ergonomic design, rapid image acquisition, and intelligent auto-exposure controls streamline clinical workflows and elevate diagnostic accuracy to the highest standards.</p>`,
  '100Ma Apr Mobile X-Ray Machine': `<p>The <strong>100mA APR Mobile X-Ray Machine</strong> is a versatile, easily maneuverable diagnostic unit designed to bring radiography directly to the patient's bedside. Equipped with Anatomical Programmed Radiography (APR), it allows technicians to simply select the body part and patient size, automatically setting the optimal exposure parameters for flawless imaging.</p><p>This mobile unit is perfect for intensive care units (ICUs), emergency rooms, and surgical wards where patient transport is difficult. Despite its compact footprint, it delivers powerful 100mA output and features electronic overload protection for unmatched safety and longevity.</p>`,
  '300mA X-Ray Machine with Floating Top Table': `<p>The <strong>300mA X-Ray Machine with Floating Top Table</strong> provides ultimate positioning flexibility for demanding clinical environments. The multi-directional floating tabletop allows technologists to smoothly and effortlessly position patients without requiring them to move, significantly improving patient comfort and workflow efficiency.</p><p>Powered by a robust 300mA generator, this system is capable of high-contrast imaging across a diverse range of radiographic studies. It is the perfect blend of ergonomic design, patient safety, and premium imaging performance.</p>`,
  '300mA Multi Position X-Ray Machine': `<p>The <strong>300mA Multi Position X-Ray Machine</strong> is an advanced imaging suite designed for comprehensive diagnostic versatility. Its unique multi-positioning stand and flexible tube head allow for seamless transitions between horizontal, vertical, and angled radiographic projections, catering to virtually any clinical requirement.</p><p>Ideal for trauma centers and busy radiology departments, it ensures rapid patient throughput while maintaining the high-resolution imaging standards expected from Sunmax's 300mA generator series.</p>`,
  '100mA Counter Balance Mobile X Ray Machine': `<p>The <strong>100mA Counter Balance Mobile X-Ray Machine</strong> is engineered for effortless mobility and precise positioning. The counter-balanced arm mechanism ensures that the X-ray tube head can be smoothly adjusted to any height or angle with zero effort, making bedside and trauma imaging highly efficient.</p><p>Compact yet powerful, this mobile unit delivers reliable 100mA output and is equipped with advanced safety features, including voltage compensation and overload protection, ensuring consistent performance in high-pressure clinical scenarios.</p>`,
  '30mA And 50mA Lightweight Portable X-Ray Machine': `<p>The <strong>Lightweight Portable X-Ray Machine (30mA / 50mA)</strong> offers unparalleled convenience for on-the-go diagnostics, veterinary applications, and field medical camps. Its ultra-compact, suitcase-style design makes it incredibly easy to transport and set up within minutes.</p><p>Despite its small size, it utilizes high-frequency technology to deliver clear, accurate X-ray images. It is the perfect solution for practitioners requiring mobile diagnostic capabilities without sacrificing image quality or patient safety.</p>`,
  'Portable Handheld X Ray Machine': `<p>The <strong>Portable Handheld X-Ray Machine</strong> is a compact, lightweight diagnostic tool designed for quick and easy imaging in various medical and dental settings. It offers high-quality X-ray images while ensuring minimal radiation exposure to patients and operators.</p><p>With its ergonomic handheld design, it provides total flexibility for emergency situations, bedside imaging, and remote locations. Powered by rechargeable high-capacity batteries, it combines portability with reliable performance for efficient, immediate diagnostics.</p>`,
  'DR14W And DR17W JPI X-Ray Detector': `<p>The <strong>JPI DR14W and DR17W Flat Panel X-Ray Detectors</strong> are premium, cassette-sized digital radiography solutions that instantly upgrade any analog X-ray machine to a full digital system. These wireless detectors offer exceptionally high Detective Quantum Efficiency (DQE), producing crystal-clear diagnostic images with minimal radiation dose.</p><p>Featuring advanced AED (Auto Exposure Detection) technology, lightweight carbon-fiber construction, and rapid image processing times, these detectors dramatically improve workflow efficiency and diagnostic accuracy in modern radiology departments.</p>`,
  '100mA Spring Balance Mobile X-Ray Unit': `<p>The <strong>100mA Spring Balance Mobile X-Ray Unit</strong> combines traditional reliability with excellent mobility. The spring-balanced articulated arm allows for smooth and secure positioning of the tube head over the patient, ensuring stable and accurate exposures.</p><p>This cost-effective mobile solution is widely trusted in nursing homes, clinics, and hospital wards for routine radiography. It features simple, user-friendly controls and robust construction designed for years of uninterrupted service.</p>`,
  '100mA Double Tank Mobile X-Ray Machine': `<p>The <strong>100mA Double Tank Mobile X-Ray Machine</strong> is a heavy-duty portable diagnostic tool designed for enhanced stability and heat dissipation during continuous use. Featuring separate tanks for the high-voltage transformer and X-ray tube, it ensures superior thermal management and extends the lifespan of the equipment.</p><p>Delivering consistent 100mA output, it provides high-quality images while minimizing patient exposure. Its sturdy mobile base allows for flexible use across hospital departments, from emergency rooms to inpatient wards.</p>`,
  'DR Holder': `<p>The <strong>Mobile DR Panel Holder Stand</strong> is an essential accessory for any digital radiography setup. Designed to securely hold expensive flat-panel detectors (like DR14W or DR17W), it offers versatile positioning for weight-bearing exams, cross-table laterals, and chest radiography.</p><p>Constructed from durable, medical-grade materials, it features smooth-rolling casters and adjustable height/tilt mechanisms, ensuring the safety of your DR panels while maximizing technologist convenience and patient comfort.</p>`
};

async function updateDescs() {
  const pool = mysql.createPool({ host: '127.0.0.1', port: 3306, database: 'smd_medicare', user: 'root', password: '' });
  let count = 0;
  
  for (const [name, desc] of Object.entries(descriptions)) {
    const [res] = await pool.query('UPDATE products SET description = ? WHERE name = ? AND brand = ?', [desc, name, 'Sunmax']);
    count += res.affectedRows;
  }
  
  console.log('Successfully updated ' + count + ' product descriptions.');
  process.exit(0);
}

updateDescs().catch(e => { console.error(e); process.exit(1); });
